"""empty message

Revision ID: 5ab4861bce9d
Revises: 
Create Date: 2019-01-28 19:33:02.625152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab4861bce9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_project', sa.Column('homepage', sa.VARCHAR(), nullable=True))
    op.add_column('github_project', sa.Column('language', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_project', 'language')
    op.drop_column('github_project', 'homepage')
    # ### end Alembic commands ###
